name: triolegendszz

on:
  workflow_dispatch:

jobs:
  build:
    name: MoonzV1
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: KomandanMarzeSlebew2
        run: |
          Invoke-WebRequest -Uri "https://github.com/tahukedelai01/setup/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Aretha3
        run: cmd /c loop.bat
